model_name_or_path: "Intel/distilbert-base-uncased-sparse-90-unstructured-pruneofa"
teacher_model_name_or_path: "distilbert-base-uncased-finetuned-sst-2-english"
task_name: "sst2"
sat: true
quantization_approach: "QuantizationAwareTraining"
learning_rate: 0.0001
num_train_epochs: 1
do_train: true
do_eval: true
# int8: true
orchestrate_optimizations: true
output_dir: "./tmp/emotion/pruning"
# max_train_samples: 16000
overwrite_output_dir: true

perf_tol: 0.03
